name: Create Artifacts

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system
        pip install pyinstaller

    - name: Build exe
      run: |
        pyinstaller mlox_linux.spec
    - name: Build lint exe
      run: |
        pyinstaller mlox_lint.spec
    - uses: actions/upload-artifact@v2
      with:
        name: mlox_linux
        path: ./dist/*


  windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system
        pip install pyinstaller

    - name: Build exe
      run: |
        pyinstaller mlox.spec 
    - uses: actions/upload-artifact@v2
      with:
        name: mlox
        path: ./dist/*


  macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system
        pip install pyinstaller

    - name: Build exe
      run: |
        pyinstaller mlox_macos.spec 
    - uses: actions/upload-artifact@v2
      with:
        name: mlox_macos
        path: ./dist/*


